import clsx from "clsx";
import { tv } from "tailwind-variants";

export const BUTTONBASE_VARIANTS = tv({
  base: clsx("mg-text-center mg-font-bold", "mg-transition-colors", "mg-block"),
  variants: {
    size: {
      xs: clsx("mg-p-2 mg-text-xs"),
      sm: clsx("mg-px-3 mg-py-2 mg-text-sm"),
      md: clsx("mg-px-4 mg-py-3 mg-text-md"),
      lg: clsx("mg-px-6 mg-py-3 mg-text-lg"),
    },
    color: {
      blue: clsx(
        "mg-text-blue-50",
        "mg-bg-blue-900",
        "hover:mg-bg-blue-1000 active:mg-bg-blue-1200",
        "[&.outline]:mg-border-blue-900 [&.outline]:mg-bg-transparent",
        "[&.outline]:mg-text-blue-900 [&.outline]:hover:mg-bg-blue-50",
        "[&.outline]:mg-border [&.outline]:active:mg-bg-blue-100",
        "[&.ghost]:mg-bg-transparent",
        "[&.ghost]:mg-text-blue-900 [&.ghost]:hover:mg-bg-blue-50",
        "[&.ghost]:active:mg-bg-blue-100",

        "dark:mg-text-blue-50",
        "dark:mg-bg-blue-600-alpha",
        "dark:hover:mg-bg-blue-700-alpha dark:hover:mg-text-white dark:active:mg-bg-blue-800-alpha",
        "dark:[&.outline]:mg-border-blue-400-alpha dark:[&.outline]:mg-bg-transparent",
        "dark:[&.outline]:mg-text-blue-50 dark:[&.outline]:hover:mg-bg-blue-500-alpha",
        "dark:[&.outline]:hover:mg-text-white",
        "dark:[&.outline]:active:mg-bg-blue-600-alpha",
        "dark:[&.outline]:mg-border",
        "dark:[&.ghost]:mg-bg-transparent",
        "dark:[&.ghost]:mg-text-blue-50 dark:[&.ghost]:hover:mg-bg-blue-500-alpha dark:[&.ghost]:hover:mg-text-white",
        "dark:[&.ghost]:active:mg-bg-blue-600-alpha"
      ),
      green: clsx(
        "mg-text-white",
        "mg-bg-green-800",
        "hover:mg-bg-green-900 active:mg-bg-green-1000",
        "[&.outline]:mg-border-green-800 [&.outline]:mg-bg-transparent",
        "[&.outline]:mg-text-green-800 [&.outline]:hover:mg-bg-green-50",
        "[&.outline]:mg-border [&.outline]:active:mg-bg-green-100",
        "[&.ghost]:mg-bg-transparent",
        "[&.ghost]:mg-text-green-800 [&.ghost]:hover:mg-bg-green-50",
        "[&.ghost]:active:mg-bg-green-100",

        "dark:mg-text-green-50",
        "dark:mg-bg-green-600-alpha",
        "dark:hover:mg-bg-green-700-alpha dark:hover:mg-text-white dark:active:mg-bg-green-800-alpha",
        "dark:[&.outline]:mg-border-green-400-alpha dark:[&.outline]:mg-bg-transparent",
        "dark:[&.outline]:mg-text-green-50 dark:[&.outline]:hover:mg-bg-green-500-alpha",
        "dark:[&.outline]:hover:mg-text-white",
        "dark:[&.outline]:active:mg-bg-green-600-alpha",
        "dark:[&.outline]:mg-border",
        "dark:[&.ghost]:mg-bg-transparent",
        "dark:[&.ghost]:mg-text-green-50 dark:[&.ghost]:hover:mg-bg-green-500-alpha dark:[&.ghost]:hover:mg-text-white",
        "dark:[&.ghost]:active:mg-bg-green-600-alpha"
      ),
      red: clsx(
        "mg-text-white",
        "mg-bg-red-900",
        "hover:mg-bg-red-1000 active:mg-bg-red-1200",
        "[&.outline]:mg-border-red-900 [&.outline]:mg-bg-transparent",
        "[&.outline]:mg-text-red-900 [&.outline]:hover:mg-bg-red-50",
        "[&.outline]:mg-border [&.outline]:active:mg-bg-red-100",
        "[&.ghost]:mg-bg-transparent",
        "[&.ghost]:mg-text-red-900 [&.ghost]:hover:mg-bg-red-50",
        "[&.ghost]:active:mg-bg-red-100",

        "dark:mg-text-red-50",
        "dark:mg-bg-red-600-alpha",
        "dark:hover:mg-bg-red-700-alpha dark:hover:mg-text-white dark:active:mg-bg-red-800-alpha",
        "dark:[&.outline]:mg-border-red-400-alpha dark:[&.outline]:mg-bg-transparent",
        "dark:[&.outline]:mg-text-red-50 dark:[&.outline]:hover:mg-bg-red-500-alpha",
        "dark:[&.outline]:hover:mg-text-white",
        "dark:[&.outline]:active:mg-bg-red-600-alpha",
        "dark:[&.outline]:mg-border",
        "dark:[&.ghost]:mg-bg-transparent",
        "dark:[&.ghost]:mg-text-red-50 dark:[&.ghost]:hover:mg-bg-red-500-alpha dark:[&.ghost]:hover:mg-text-white",
        "dark:[&.ghost]:active:mg-bg-red-600-alpha"
      ),
      yellow: clsx(
        "mg-text-white",
        "mg-bg-yellow-800",
        "hover:mg-bg-yellow-1000 active:mg-bg-yellow-1200",
        "[&.outline]:mg-border-yellow-800 [&.outline]:mg-bg-transparent",
        "[&.outline]:mg-text-yellow-800 [&.outline]:hover:mg-bg-yellow-50",
        "[&.outline]:mg-border [&.outline]:active:mg-bg-yellow-100",
        "[&.ghost]:mg-bg-transparent",
        "[&.ghost]:mg-text-yellow-900 [&.ghost]:hover:mg-bg-yellow-50",
        "[&.ghost]:active:mg-bg-yellow-100",

        "dark:mg-text-yellow-50",
        "dark:mg-bg-yellow-600-alpha",
        "dark:hover:mg-bg-yellow-700-alpha dark:hover:mg-text-white dark:active:mg-bg-yellow-800-alpha",
        "dark:[&.outline]:mg-border-yellow-400-alpha dark:[&.outline]:mg-bg-transparent",
        "dark:[&.outline]:mg-text-yellow-50 dark:[&.outline]:hover:mg-bg-yellow-500-alpha",
        "dark:[&.outline]:hover:mg-text-white",
        "dark:[&.outline]:active:mg-bg-yellow-600-alpha",
        "dark:[&.outline]:mg-border",
        "dark:[&.ghost]:mg-bg-transparent",
        "dark:[&.ghost]:mg-text-yellow-50 dark:[&.ghost]:hover:mg-bg-yellow-500-alpha dark:[&.ghost]:hover:mg-text-white",
        "dark:[&.ghost]:active:mg-bg-yellow-600-alpha"
      ),
      lime: clsx(
        "mg-text-white",
        "mg-bg-lime-700",
        "hover:mg-bg-lime-800 active:mg-bg-lime-900",
        "[&.outline]:mg-border-lime-700 [&.outline]:mg-bg-transparent",
        "[&.outline]:mg-text-lime-700 [&.outline]:hover:mg-bg-lime-50",
        "[&.outline]:mg-border [&.outline]:active:mg-bg-lime-100",
        "[&.ghost]:mg-bg-transparent",
        "[&.ghost]:mg-text-lime-700 [&.ghost]:hover:mg-bg-lime-50",
        "[&.ghost]:active:mg-bg-lime-100",

        "dark:mg-text-lime-50",
        "dark:mg-bg-lime-600-alpha",
        "dark:hover:mg-bg-lime-700-alpha dark:hover:mg-text-white dark:active:mg-bg-lime-800-alpha",
        "dark:[&.outline]:mg-border-lime-400-alpha dark:[&.outline]:mg-bg-transparent",
        "dark:[&.outline]:mg-text-lime-50 dark:[&.outline]:hover:mg-bg-lime-500-alpha",
        "dark:[&.outline]:hover:mg-text-white",
        "dark:[&.outline]:active:mg-bg-lime-600-alpha",
        "dark:[&.outline]:mg-border",
        "dark:[&.ghost]:mg-bg-transparent",
        "dark:[&.ghost]:mg-text-lime-50 dark:[&.ghost]:hover:mg-bg-lime-500-alpha dark:[&.ghost]:hover:mg-text-white",
        "dark:[&.ghost]:active:mg-bg-lime-600-alpha"
      ),
      orange: clsx(
        "mg-text-white",
        "mg-bg-orange-800",
        "hover:mg-bg-orange-900 active:mg-bg-orange-1000",
        "[&.outline]:mg-border-orange-800 [&.outline]:mg-bg-transparent",
        "[&.outline]:mg-text-orange-800 [&.outline]:hover:mg-bg-orange-50",
        "[&.outline]:mg-border [&.outline]:active:mg-bg-orange-100",
        "[&.ghost]:mg-bg-transparent",
        "[&.ghost]:mg-text-orange-800 [&.ghost]:hover:mg-bg-orange-50",
        "[&.ghost]:active:mg-bg-orange-100",

        "dark:mg-text-orange-50",
        "dark:mg-bg-orange-600-alpha",
        "dark:hover:mg-bg-orange-700-alpha dark:hover:mg-text-white dark:active:mg-bg-orange-800-alpha",
        "dark:[&.outline]:mg-border-orange-400-alpha dark:[&.outline]:mg-bg-transparent",
        "dark:[&.outline]:mg-text-orange-50 dark:[&.outline]:hover:mg-bg-orange-500-alpha",
        "dark:[&.outline]:hover:mg-text-white",
        "dark:[&.outline]:active:mg-bg-orange-600-alpha",
        "dark:[&.outline]:mg-border",
        "dark:[&.ghost]:mg-bg-transparent",
        "dark:[&.ghost]:mg-text-orange-50 dark:[&.ghost]:hover:mg-bg-orange-500-alpha dark:[&.ghost]:hover:mg-text-white",
        "dark:[&.ghost]:active:mg-bg-orange-600-alpha"
      ),
      purple: clsx(
        "mg-text-white",
        "mg-bg-purple-900",
        "hover:mg-bg-purple-1000 active:mg-bg-purple-1200",
        "[&.outline]:mg-border-purple-900 [&.outline]:mg-bg-transparent",
        "[&.outline]:mg-text-purple-900 [&.outline]:hover:mg-bg-purple-50",
        "[&.outline]:mg-border [&.outline]:active:mg-bg-purple-100",
        "[&.ghost]:mg-bg-transparent",
        "[&.ghost]:mg-text-purple-900 [&.ghost]:hover:mg-bg-purple-50",
        "[&.ghost]:active:mg-bg-purple-100",

        "dark:mg-text-purple-50",
        "dark:mg-bg-purple-600-alpha",
        "dark:hover:mg-bg-purple-700-alpha dark:hover:mg-text-white dark:active:mg-bg-purple-800-alpha",
        "dark:[&.outline]:mg-border-purple-400-alpha dark:[&.outline]:mg-bg-transparent",
        "dark:[&.outline]:mg-text-purple-50 dark:[&.outline]:hover:mg-bg-purple-500-alpha",
        "dark:[&.outline]:hover:mg-text-white",
        "dark:[&.outline]:active:mg-bg-purple-600-alpha",
        "dark:[&.outline]:mg-border",
        "dark:[&.ghost]:mg-bg-transparent",
        "dark:[&.ghost]:mg-text-purple-50 dark:[&.ghost]:hover:mg-bg-purple-500-alpha dark:[&.ghost]:hover:mg-text-white",
        "dark:[&.ghost]:active:mg-bg-purple-600-alpha"
      ),
      gray: clsx(
        "mg-text-white",
        "mg-bg-black",
        "hover:mg-bg-gray-900 active:mg-bg-gray-800",
        "[&.outline]:mg-border-black [&.outline]:mg-bg-transparent",
        "[&.outline]:mg-text-black [&.outline]:hover:mg-bg-gray-50",
        "[&.outline]:mg-border [&.outline]:active:mg-bg-gray-100",
        "[&.ghost]:mg-bg-transparent",
        "[&.ghost]:mg-text-black [&.ghost]:hover:mg-bg-gray-50",
        "[&.ghost]:active:mg-bg-gray-100",

        "dark:mg-text-gray-50",
        "dark:mg-bg-gray-600-alpha",
        "dark:hover:mg-bg-gray-700-alpha dark:hover:mg-text-white dark:active:mg-bg-gray-800-alpha",
        "dark:[&.outline]:mg-border-gray-400-alpha dark:[&.outline]:mg-bg-transparent",
        "dark:[&.outline]:mg-text-gray-50 dark:[&.outline]:hover:mg-bg-gray-500-alpha",
        "dark:[&.outline]:hover:mg-text-white",
        "dark:[&.outline]:active:mg-bg-gray-600-alpha",
        "dark:[&.outline]:mg-border",
        "dark:[&.ghost]:mg-bg-transparent",
        "dark:[&.ghost]:mg-text-gray-50 dark:[&.ghost]:hover:mg-bg-gray-500-alpha dark:[&.ghost]:hover:mg-text-white",
        "dark:[&.ghost]:active:mg-bg-gray-600-alpha"
      ),
    },
    pill: {
      true: clsx("mg-rounded-full"),
      false: clsx("mg-rounded-md"),
    },
  },
});
